autoencoder:
  target: tok.models.vqgan.VQModel
  params:
    use_connector: true
    encoder:
      target: tok.models.backbone.diffusion.Encoder
      params:
        double_z: false
        z_channels: 256
        resolution: 256
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult: [1, 1, 2, 2, 4]
        num_res_blocks: 2
        attn_resolutions: [16]
        dropout: 0.0
    decoder:
      target: tok.models.backbone.diffusion.Decoder
      params:
        double_z: false
        z_channels: 256
        resolution: 256
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult: [1, 1, 2, 2, 4]
        num_res_blocks: 2
        attn_resolutions: [16]
        dropout: 0.0
    quantize:
      target: tok.models.quantizer.VectorQuantizer
      params:
        n_e: 16384
        e_dim: 256
        beta: 0.25
        use_proj: true
        fix_codes: false
        start_quantize_steps: null
        num_head: 4
    loss:
      target: tok.losses.aeloss_disc.AELossWithDisc
      params:
        loss_l1_weight: 1.0
        loss_l2_weight: 1.0
        loss_p_weight: 3.0
        loss_q_weight: 1.0
        loss_g_weight: 1.0
        loss_d_weight: 1.0
        disc_in_channels: 3
        disc_num_layers: 3
        disc_start: 150000
